routes/web.php
<?php

use Facade\FlareClient\View;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/{any}', function () {
//     return View('welcome');
// })->where('any', '.*');

Route::get('/', function(){
    return View('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//========================== EMAIL ===================================

//send mail
Route::get('/order/{id}', 'OrderController@ship')->name('mail');

//Review Mail tempalte
Route::get('/mailable', function () {
    $order = App\Order::find(1);
    return new App\Mail\OrderShipped($order);
});

//Send Mail via Queue
Route::get('/queue/{id}', 'OrderController@queueShip')->name('queue');

//Send Mail Notification
Route::get('/notification/{id}', 'OrderController@sendNotification')->name('notification');


//======================= DATABASE Notifications ===================
//Gửi notification (id=order_id)
Route::get('/db-notification/{id}', 'OrderController@sendDatabaseNotification')->name('db-notification');

//Đánh dấu các notification đã đọc của user (id=user_id)
Route::get('/mark-notification/{id}', 'OrderController@markNotification')->name('mark-notification');

//========================== Repositories ============================//
Route::resource('/news', 'NewsController');


//========================== Template ============================//
Route::get('/table-sm', function(){
    return view('template.table-sm');
});

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $table = 'news';
    protected $fillable = ['title', 'content', 'url', 'image'];
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\News;
use App\Repositories\Contracts\INews;
use Illuminate\Support\Str;

class NewsController extends Controller
{
    protected $newsRepository;

    public function __construct(INews $newsRepository)
    {
        $this->newsRepository = $newsRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            return $this->newsRepository->datatable();
        }
        return view('news.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('news.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $groups = $this->newsRepository->create([
            'title' => $request->input('title'),
            'content' => $request->input('content'),
            'url' =>  Str::slug($request->title, '-'),
            'image' => $request->image
        ]);
        return redirect()->route('news.index')->with([
            'flash_level'   => 'success',
            'flash_message' => 'Add success'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $news = $this->newsRepository->find($id);
        return view('news.edit', compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->newsRepository->update($id,[
            'title' => $request->input('title'),
            'content' => $request->input('content'),
            'url' =>  Str::slug($request->slug, '-')
        ]);
        return redirect()->route('news.index')->with([
            'flash_level'   => 'success',
            'flash_message' => 'Update success'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if($this->newsRepository->delete($id)){
            return response()->json([
                'row_id' => $id,
                'message' => 'News deleted successfully',
                'status_code' => 200
            ], 200);
        }
        else{
            return response()->json([
                'row_id' => $id,
                'message' => 'Some error occured, please try again',
                'status_code' => 500
            ], 500);
        }
    }
}

resources/views/news/add.blade.php
@extends('layout.app')

@section('content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">News-add</h1>
        <div class="card mb-4">
            <div class="card-header"><i class="fas fa-table mr-1"></i>Form</div>
            <div class="card-body">
                <form method="POST" action="{{ route('news.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group @error('title') has-danger @enderror">
                        <label for="name">Title</label>
                        <input type="text" name="title" value="{{ old('title') }}" class="form-control">
                        @error('title')<span class="text-danger">{{ $message }}</span>@enderror
                    </div>
                    <div class="form-group">
                        <label for="content">Content</label>
                        <textarea class="form-control" name="content" rows="3">{{ old('content') }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="banner">Image</label>
                        <input type="file" name="image"/>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Save">
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/news/edit.blade.php
@extends('layout.app')

@section('content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">News-add</h1>
        <div class="card mb-4">
            <div class="card-header"><i class="fas fa-table mr-1"></i>Form</div>
            <div class="card-body">
                <form method="POST" action="{{ route('news.update', $news->id) }}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group @error('title') has-danger @enderror">
                        <label for="title">Title</label>
                        <input type="text" name="title" value="{{ old('title', $news->title) }}" class="form-control">
                        @error('title')<span class="text-danger">{{ $message }}</span>@enderror
                    </div>
                    <div class="form-group">
                        <label for="content">Content</label>
                        <textarea class="form-control" name="content" rows="3">{{ old('content', $news->content) }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="banner">Image</label>
                        <input type="file" name="image"/>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Save">
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/news/index.blade.php
@extends('layout.app')

@section('content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Tables</h1>
        <div class="card mb-4">
            <div class="card-header"><i class="fas fa-table mr-1"></i>DataTable Example</div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Content</th>
                                <th>Image</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>

<!-- Confirm dialog-->
<div class="modal fade" id="confirmDeleteItem" tabindex="-1" role="dialog" aria-labelledby="modelLabel"
aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-warning">
                <strong>{{__('action.delete_confirm')}}</strong>
            </div>
            <div id="confirmMessage" class="modal-body">
                {{__('action.delete_sure')}}
            </div>
            <div class="modal-footer">
                <button type="button" id="confirmCancel" class="btn btn-default btn-cancel"
                        data-dismiss="modal">
                    {{__('action.cancel')}}
                </button>
                <button type="button" id="btnConfirmDelete" class="btn btn-danger btn-ok" onclick="deleteItem($(this).val())">
                    {{__('action.delete')}}
                </button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('page-scripts')
<script>
    $('#dataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('news.index') }}",
        columns: [
            { data: 'title', name: 'title' },
            { data: 'content', name: 'content' },
            { data: 'image', name: 'image', orderable: false, searchable: false},
        ],
        columnDefs: [{
            "targets": 3, 
            "data": null,
            "render": function (data) {
                edit_href = data.edit_url;
                delete_event = ' onclick = checkItemExisted(' + data.id + ') ';
                return '<a class="btn btn-primary btn-sm" href=' + edit_href + '><span class="fa fa-edit"></span></a> ' +
                '<button class="btn btn-sm btn-danger" ' + delete_event + 'id="row_' + data.id + '" data-toggle="modal" data-target="#confirmDeleteItem" >' +
                    '<span class="fa fa-trash" ></span></button> ';
            }
        }],
    });

    function checkItemExisted(id) {
        $('#btnConfirmDelete').val(id);
    }

    function deleteItem(id) {
        const URL =  "http://localhost/global/public/news/";
        let request = $.ajax({
            url: URL + id,
            method: "DELETE",
            data: {
                "_token" : "{{ csrf_token() }}"
            }
        }).done(function (data) {
            $("#confirmDeleteItem").modal('hide');
            if(data.status_code == 500){
                iziToast.success({
                    title: 'Error',
                    message: data.message,
                    position: 'topRight'
                });
            }
            else {
                $(`#row_${data.row_id}`).closest("tr").remove();
                iziToast.success({
                    title: 'Message',
                    message: data.message,
                    position: 'topRight'
                });
            }
        });
    }
</script>
@endpush